### ISSUE TITLE
GOSA9 - Upcoming events

### ISSUE THREAD

**Issue by ashish11chawda** [GameofSource-GFG/Android-Development#10]
#### Description
Add a screen to show upcoming events and fetch it from firebase field 'event-data'

**Comment by rithik-dev** [comment]
I can work on it

**Comment by ashish11chawda** [comment]
@rithik-dev You can start working on this issue!

If you have any doubts or queries you can comment here or ask us on the WhatsApp group.

**Comment by geekyaditya100** [comment]
@rithik-dev Your PR is successfully merged and score will be assigned as 10 Points to this.
