### ISSUE TITLE
GOSA1 - UI for Registration with email and with google auth

### ISSUE THREAD

**Issue by ashish11chawda** [GameofSource-GFG/Android-Development#2]
#### Description
GeeksforGeeks Andriod App registration with the help of email and other credentials or with help of google authentication. Create text fields to take relevant user data and create a user in user_data field in firebase. And also create a button to activate google authentication.

**Comment by muskan-888** [comment]
kindly assign it to me

**Comment by Rishav0907** [comment]
I want to work on it

**Comment by rithik-dev** [comment]
I can work on it

**Comment by ashish11chawda** [comment]
@muskan-888 You can start working on this issue
If you have any doubts or queries, you can comment here or ask us on the WhatsApp group

**Comment by singhtaran1005** [comment]
plz assign it to me!

**Comment by geekyaditya100** [comment]
@singhtaran1005 thank you for the contribution. you have recieved 5 points for the contribution. Keep it up
