### ISSUE TITLE
GOSA10 - Create custom app drawer

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#29]
Create a Custom App drawer and place it in the widgets folder.

**Comment by kanhayaKy** [comment]
in for this

**Comment by singhtaran1005** [comment]
assign me

**Comment by Rishav0907** [comment]
please assign this to me

**Comment by geekyaditya100** [comment]
@kanhayaKy work on this issue buddy. All the best

**Comment by geekyaditya100** [comment]
@kanhayaKy thank you for the contribution. your PR is successfully merged. You have received 5 points for the contribution
