### ISSUE TITLE
GOSA2 - UI for login with email and password

### ISSUE THREAD

**Issue by ashish11chawda** [GameofSource-GFG/Android-Development#3]
#### Description
GeeksforGeeks Andriod App login the user with email and password. Create text fields to take email and password and authenticate the user using firebase.

**Comment by ShrutiJ-01** [comment]
please assign this to me

**Comment by Rishav0907** [comment]
I can work on it

**Comment by muskan-888** [comment]
can work on it

**Comment by rithik-dev** [comment]
I can work on it

**Comment by singhtaran1005** [comment]
assign me

**Comment by ashish11chawda** [comment]
@ShrutiJ-01 You can start working on this issue!
If you have any doubts or queries you can comment here or ask us on the WhatsApp group.

**Comment by ashish11chawda** [comment]
@singhtaran1005 You can see other issues also if it fits your skillset

**Comment by geekyaditya100** [comment]
@ShrutiJ-01 thank you for the contribution. We have success merged your request. Nice ui. You have recieved 5 points for the contribution
