### ISSUE TITLE
GOSA11 - Load the dynamic committee members data from firebase 

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#30]
Fetch data from firebase and display in the app (UI for this is already done).

**Comment by singhtaran1005** [comment]
assign me

**Comment by geekyaditya100** [comment]
@singhtaran1005 you can work on this issue.

**Comment by geekyaditya100** [comment]
@singhtaran1005 we have successfully merged your pull request. Thank you for the contribution.
You have received 10 points for the contribution.
