### ISSUE TITLE
GOSA12 - UI Newsletter subscription

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#31]
Create a widget for entering an email address and a send button with validation for email then place it in the components folder.

**Comment by gharshg29** [comment]
assign me !!

**Comment by singhtaran1005** [comment]
assign me plz!!

**Comment by ShrutiJ-01** [comment]
please assign this to me!

**Comment by geekyaditya100** [comment]
@gharshg29 work on this issue

**Comment by geekyaditya100** [comment]
@gharshg29 Thank you for the contribution. Your pull request has been successfully merged. You have received 5 Points for the contribution.
