### ISSUE TITLE
GOSA13 - Notification on the date of event 

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#32]
Send notification to the user to remind them of the date of the event. (Use One Signal)

**Comment by amanv8060** [comment]
Will it be dynamic , like on document changes or we have to do it just manually , through firebase console?

**Comment by VarunAthreya** [comment]
The event data is already present in the firebase database and on the basis of it, the notification must be sent.

**Comment by amanv8060** [comment]
I can try this

**Comment by RakeshSeervi** [comment]
I am done with my assigned issue. I can work on this!

**Comment by singhtaran1005** [comment]
assign me ! 

plz

**Comment by geekyaditya100** [comment]
@amanv8060 you can work on  this.

**Comment by amanv8060** [comment]
I have not registered for the competition .

**Comment by geekyaditya100** [comment]
@amanv8060 registrations are still available. You can register now in eventribe and contribute. All the best

**Comment by singhtaran1005** [comment]
assign me plz

**Comment by sanjanarp** [comment]
I'm up for this

**Comment by singhtaran1005** [comment]
getting it with Firebase functions is bit difficult

**Comment by RakeshSeervi** [comment]
Would like to give a try

**Comment by VarunAthreya** [comment]
@RakeshSeervi you can work on this.

**Comment by geekyaditya100** [comment]
@RakeshSeervi thank you for the contribution. You have received 10 points for the contribution. We have merged your pr successfully
