### ISSUE TITLE
GOSA14 - Set theme data in main.dart

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#33]
Set basic theming for the app as `primaryColor: Colors.white` and `accentColor: Color(0xFF2F8D46)` and change theming of all widgets/screens accordingly and also remove font styles/family.

**Comment by gharshg29** [comment]
Assign me, I can do this !!

**Comment by ShrutiJ-01** [comment]
please assign this to me!

**Comment by VarunAthreya** [comment]
@ShrutiJ-01 you can start working on this issue.

**Comment by ShrutiJ-01** [comment]
Thanks! After removing fonts/family, is there any font that must be applied to text throughout the application?

**Comment by VarunAthreya** [comment]
No. Let there be the default font.

**Comment by ShrutiJ-01** [comment]
I have made all the changes required. Only the mission and vision screen is left which has a green gradient as its background. But when I try to run it on my emulator it says "multiple widgets used the same global key".I haven't edited any code for that screen yet. Please tell me where I must look to resolve the error

**Comment by ShrutiJ-01** [comment]
resolved the error!

**Comment by geekyaditya100** [comment]
@ShrutiJ-01 Thank you for the contribution. Your pull request has been merged successfully. You have received 5 points for the contribution.
