### ISSUE TITLE
GOSA15 -  Create routing for screens in main.dart

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#34]
Create routing for all the screens.
Steps: 
1. Create a static variable `routeName` with value `"/screenName"` in respective screens.
2. Add the `routeName` to main.dart

**Comment by singhtaran1005** [comment]
assign me

**Comment by ShrutiJ-01** [comment]
please assign this to me

**Comment by singhtaran1005** [comment]
plz assign me this!

**Comment by RakeshSeervi** [comment]
Can work on this!

**Comment by VarunAthreya** [comment]
@RakeshSeervi  you can work on this issue.

**Comment by geekyaditya100** [comment]
@RakeshSeervi Thank you for the contribution, We have successfully merged your Pull request.
You have received 5 points for the contribution. Keep it up.
