### ISSUE TITLE
GOSA3 - UI for about section

### ISSUE THREAD

**Issue by ashish11chawda** [GameofSource-GFG/Android-Development#4]
#### Description
GeeksforGeeks Andriod App About page. This page will have a description of the student chapter.

You can use lorem placeholder text here for content

**Comment by Rishav0907** [comment]
Pls assign this to me

**Comment by muskan-888** [comment]
I can work on this

**Comment by gharshg29** [comment]
Please assign it to me !!

**Comment by ashish11chawda** [comment]
@Rishav0907 You can start working on this issue!
If you have any doubts or queries you can comment here or ask us on the WhatsApp group.

**Comment by geekyaditya100** [comment]
@Rishav0907 your contribution is successfully registered. Thanks for your update.
You have recieved 5 points for the contribution. Keep it up
