### ISSUE TITLE
GOSA16 - Make User registration in firebase

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#45]
Connect user registration UI to firebase and also add registration through google sign in.

**Comment by rithik-dev** [comment]
assign me

**Comment by singhtaran1005** [comment]
assign me plz

**Comment by geekyaditya100** [comment]
@singhtaran1005 work on this

**Comment by geekyaditya100** [comment]
@singhtaran1005 Thank you for the contribution. You have recieved 10 points for the contribution. Your pull request is merged successfully
