### ISSUE TITLE
GOSA17 - Make User login in firebase

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#46]
Connect user login UI to firebase and connect the `Register Here` to registration UI by using pushNamed (use the static variable `routeName`  in the class).

**Comment by singhtaran1005** [comment]
assign me

**Comment by rithik-dev** [comment]
assign me

**Comment by geekyaditya100** [comment]
@rithik-dev work on this

**Comment by geekyaditya100** [comment]
@rithik-dev Your Pull request is successfully merged. Thank you for the contribution and you have recieved 10 points for the contribution
