### ISSUE TITLE
GOSA18 - Connect Contact US form to firebase

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#47]
Connect Contact US form to firebase with all given details

**Comment by RakeshSeervi** [comment]
Can work on this!

**Comment by geekyaditya100** [comment]
@RakeshSeervi you can work on this issue

**Comment by geekyaditya100** [comment]
@RakeshSeervi we have successfully merged your pull request. Thank you for the contribution. You have recieved 5 points for the contribution
