### ISSUE TITLE
GOSA19 - Make Field for newsletter in fireabse

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#48]
Add a field in firebase `newsletter` and save all the emails entered.

**Comment by singhtaran1005** [comment]
assign me

**Comment by gharshg29** [comment]
assign me !

**Comment by geekyaditya100** [comment]
@gharshg29 work on this

**Comment by gharshg29** [comment]
Due to some unavoidable circumstances, I won't be able to continue with this issue. I am really sorry for the inconvenience caused.

**Comment by rithik-dev** [comment]
assign me

**Comment by VarunAthreya** [comment]
@rithik-dev you can start working on this!

**Comment by rithik-dev** [comment]
I have to add the emails to a new collection?

**Comment by geekyaditya100** [comment]
@rithik-dev your pull request is successfully merged. Thank you for the contribution. You have received 5 Points for the contribution
