### ISSUE TITLE
GOSA20 - Connect the screens to app drawer

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#49]
Connect all the screens to the App drawer and add the app drawer in widgets to all the screens.

**Comment by singhtaran1005** [comment]
assign me

**Comment by rithik-dev** [comment]
assign me

**Comment by RakeshSeervi** [comment]
Can work on this!

**Comment by gharshg29** [comment]
assign me

**Comment by kanhayaKy** [comment]
in for this

**Comment by geekyaditya100** [comment]
@kanhayaKy work on this

**Comment by ShrutiJ-01** [comment]
Can work on this!

**Comment by geekyaditya100** [comment]
@kanhayaKy Thank you for the contribution. you have received 10 points for the contribution. your pull request is successfully merged.
