### ISSUE TITLE
GOSA4 - UI for Mission and Vision section

### ISSUE THREAD

**Issue by ashish11chawda** [GameofSource-GFG/Android-Development#5]
#### Description
Geeksforgeeks student chapter Mission and Vision section.

You can use lorem placeholder text for content.

**Comment by Rishav0907** [comment]
Please assign this to me

**Comment by ShrutiJ-01** [comment]
please assign this to me

**Comment by muskan-888** [comment]
kindly assign it to me

**Comment by gharshg29** [comment]
Please assign it to me !!

**Comment by ashish11chawda** [comment]
@gharshg29 You can start working on this issue!
If you have any doubts or queries you can comment here or ask us on the WhatsApp group.

**Comment by geekyaditya100** [comment]
@gharshg29 thank you for the contribution. You have recieved 5 points for the contribution. Keep it up
