### ISSUE TITLE
GOSA21 - Add splash screen

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#58]
Add native splash screen to App using the package (flutter_native_splash).

**Comment by singhtaran1005** [comment]
assign me

**Comment by gharshg29** [comment]
assign me

**Comment by VarunAthreya** [comment]
@singhtaran1005 you can work on this

**Comment by geekyaditya100** [comment]
@singhtaran1005 thank you for the contribution. you have recieved 5 points for the contribution. We have merged your pr successfully.
