### ISSUE TITLE
GOSA22 - Add Home Page

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#59]
Add home page which contains UI for announcements and add the app drawer to all other screens and add `routeName` of the home screen to the app drawer.

**Comment by rithik-dev** [comment]
assign me

**Comment by sanjanarp** [comment]
I'm up for this

**Comment by kanhayaKy** [comment]
Up for this

**Comment by ShrutiJ-01** [comment]
please assign to me!!

**Comment by VarunAthreya** [comment]
@rithik-dev you can start working on it

**Comment by geekyaditya100** [comment]
@rithik-dev  thank you for the contribution. You have recieved 5 points for the contribution. We have merged your pull request successfully
