### ISSUE TITLE
GOSA5 - UI for Committee Members section

### ISSUE THREAD

**Issue by ashish11chawda** [GameofSource-GFG/Android-Development#6]
#### Description
GeeksforGeeks student chapter committee member details.

You can create cards for members or be creative and do something innovative.

**Comment by ShrutiJ-01** [comment]
please assign this to me

**Comment by gharshg29** [comment]
Please assign it to me, I can work on it !!

**Comment by singhtaran1005** [comment]
Assign me plz

**Comment by geekyaditya100** [comment]
@singhtaran1005 Thank you for the contribution. Your issue is merged successfully and pr is accepted.
You have recieved 5 Points for the contribution
