### ISSUE TITLE
GOSA23 - Add Registration UI

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#60]
Add Event registration UI which should have a name, USN, email, event name. And add it to the App Drawer.

**Comment by gharshg29** [comment]
assign me

**Comment by kanhayaKy** [comment]
Up for this

**Comment by ShrutiJ-01** [comment]
assign me

**Comment by VarunAthreya** [comment]
@kanhayaKy you can start working on it

**Comment by geekyaditya100** [comment]
@kanhayaKy Thank you for the contribution, You have recieved 5 points for the contribution. we have merged your pr successfully.
