### ISSUE TITLE
GOSA24 - Add logout functionality

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#69]
Add logout button and corresponding firebase function in App drawer.

**Comment by singhtaran1005** [comment]
assign me

**Comment by geekyaditya100** [comment]
@singhtaran1005 express

**Comment by singhtaran1005** [comment]
express?

**Comment by singhtaran1005** [comment]
assign me

**Comment by rithik-dev** [comment]
assign me

**Comment by VarunAthreya** [comment]
@rithik-dev you can start working on this.

**Comment by geekyaditya100** [comment]
@rithik-dev thank you for the contribution. You have recieved 5 points for the contribution. We merged your pr successfully
