### ISSUE TITLE
GOSA6 - Contact us form

### ISSUE THREAD

**Issue by ashish11chawda** [GameofSource-GFG/Android-Development#7]
#### Description
GeeksforGeeks student chapter contacts us section. Create a form with name, email, phone number, and message to the student chapter

**Comment by rithik-dev** [comment]
I can work on it

**Comment by Rishav0907** [comment]
can work on it. assign it to me

**Comment by ankittripathi31** [comment]
Please assign this to me

**Comment by geekyaditya100** [comment]
@ankittripathi31 you can work on this issue

**Comment by kanhayaKy** [comment]
Up for this one

**Comment by VarunAthreya** [comment]
This issue is free now!

**Comment by rithik-dev** [comment]
I can do it

**Comment by VarunAthreya** [comment]
@rithik-dev you can work on this issue

**Comment by geekyaditya100** [comment]
@rithik-dev Thank you for the contribution we have successfully merged your Pull request.
You have received 5 points for the contribution keep it up
