### ISSUE TITLE
GOSA25 - Connect Registration form to firebase

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#70]
Connect Registration form to firebase with all given details.

**Comment by singhtaran1005** [comment]
assign me

**Comment by singhtaran1005** [comment]
assign me this plz

**Comment by VarunAthreya** [comment]
@singhtaran1005  you can start working on this.

**Comment by geekyaditya100** [comment]
@singhtaran1005 thank you for the contribution. We have merged your pr successfully. You have recieved 5 points for the contribution
