### ISSUE TITLE
GOSA26 - Connect announcement details to fireabase 

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#71]
Connect announcement card to firebase with all given details.

**Comment by RakeshSeervi** [comment]
Can work on this!

**Comment by VarunAthreya** [comment]
@RakeshSeervi  you can start working on this

**Comment by geekyaditya100** [comment]
@RakeshSeervi Thank you for the contribution. We have successfully merged your Pull Request. You have received 10 points for the contribution.
