### ISSUE TITLE
GOSA27 - In upcoming event page show only events which are not finished 

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#72]
Add a new field to the collection called `finished` and show based on that.

**Comment by rithik-dev** [comment]
assign me

**Comment by RakeshSeervi** [comment]
Can work on this!

**Comment by geekyaditya100** [comment]
@rithik-dev you can now work on this issue

**Comment by geekyaditya100** [comment]
@rithik-dev Thank you for the contribution. We have successfully merged your pull request. You have received 10 points for the contribution.
