### ISSUE TITLE
GOSA28 - Add register now button on event card

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#73]
The button must push to the registration screen.

**Comment by singhtaran1005** [comment]
assign me

**Comment by geekyaditya100** [comment]
@singhtaran1005 work on this issue

**Comment by geekyaditya100** [comment]
@singhtaran1005 thank you for the contribution. You have received 5 points for the contribution. we have merged your pull request successfully.
