### ISSUE TITLE
GOSA29 - Re-arrange app drawer

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#74]
Re-arrange in order of Home, About Us, Team, Events, Registration, Contact.

**Comment by singhtaran1005** [comment]
assign me

**Comment by rithik-dev** [comment]
assign plz

**Comment by geekyaditya100** [comment]
@rithik-dev work on this bug

**Comment by geekyaditya100** [comment]
@rithik-dev  thank you for the contribution. You have received 5 points for the contribution. We have successfully merged your pull request.
