### ISSUE TITLE
GOSA30 - Add share feature in App Drawer

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#75]
Use the `share` package and Add this link `https://github.com/GameofSource-GFG/Android-Development` with instructions to download the apk by going to workflow and then artifacts and download it from there.

**Comment by singhtaran1005** [comment]
assign me

**Comment by geekyaditya100** [comment]
@singhtaran1005 work on this issue

**Comment by RakeshSeervi** [comment]
Can work on this!

**Comment by VarunAthreya** [comment]
@RakeshSeervi  you can start working on this.

**Comment by geekyaditya100** [comment]
@RakeshSeervi thank you for the contribution. We have merged your pr successfully. You have received 5 points for the contribution
