### ISSUE TITLE
GOSA7 - Student chapter Google map coordinates at contact us

### ISSUE THREAD

**Issue by ashish11chawda** [GameofSource-GFG/Android-Development#8]
#### Description
GeeksforGeeks Student Chapter Google Map should be added to the contact us form.

**Comment by RakeshSeervi** [comment]
Would like to work on this

**Comment by kanhayaKy** [comment]
Up for this one

**Comment by geekyaditya100** [comment]
@RakeshSeervi Thank you for the contribution. We have successfully merged your Pull request.
You got 10 points for the contribution. Keep up the same pace.
