### ISSUE TITLE
GOSA32 - Add App icon

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#87]
Add custom app icon for both iOS and Android (use gfg logo).

**Comment by sanjanarp** [comment]
Please assign me!

**Comment by rithik-dev** [comment]
assign plz

**Comment by ShrutiJ-01** [comment]
Assign me please

**Comment by gharshg29** [comment]
Assign me !!

**Comment by VarunAthreya** [comment]
@sanjanarp you can start working on this.

**Comment by geekyaditya100** [comment]
@sanjanarp we have merged your pull request. You have received 5 points for the contribution. Thank you for the contribution.
