### ISSUE TITLE
GOSA33 - Move Sign-In from google button

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#88]
Move SignIn from google button from signup screen to login screen.

**Comment by singhtaran1005** [comment]
asssign me

**Comment by ShrutiJ-01** [comment]
Assign me

**Comment by rithik-dev** [comment]
assign plz

**Comment by VarunAthreya** [comment]
@singhtaran1005 you can start working on this.

**Comment by geekyaditya100** [comment]
@singhtaran1005 thank you for the contribution. You have received 5 points for the contribution. We have merged your PR successfully.
