### ISSUE TITLE
GOSA34 - Add loading while signup and login

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#89]
Add a circular loading indicator while the process of signup/login is going on.

**Comment by rithik-dev** [comment]
assign plz

**Comment by VarunAthreya** [comment]
@rithik-dev  you can start working on this

**Comment by geekyaditya100** [comment]
@rithik-dev thank you for the contribution. You have received 10 points for the contribution. We have merged your PR successfully.
