### ISSUE TITLE
GOSA8 - Social Media Links

### ISSUE THREAD

**Issue by ashish11chawda** [GameofSource-GFG/Android-Development#9]
#### Description
Add social media icons and their respective website. Use package 'url_launcher' to complete the task.

**Comment by ShrutiJ-01** [comment]
please assign this to me.I can do it

**Comment by Rishav0907** [comment]
Please assign this to me

**Comment by muskan-888** [comment]
i can do this

**Comment by singhtaran1005** [comment]
Assign me

**Comment by RakeshSeervi** [comment]
I am up for this.

**Comment by ashish11chawda** [comment]
@singhtaran1005 You can please start working on this issue!
If you have any doubts or queries, you can comment here or ask us on the WhatsApp group.

**Comment by geekyaditya100** [comment]
@singhtaran1005 Your commit is successful and you receive 5 Points for the commit.
