### ISSUE TITLE
GOSA35 - Rename the app

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#95]
Rename the android app from `our_gfg` to `OurGfG.`

**Comment by sanjanarp** [comment]
Up for this

**Comment by VarunAthreya** [comment]
@sanjanarp you can start working on this.

**Comment by geekyaditya100** [comment]
@sanjanarp Thank you for the contribution. You have received 5 points for the contribution. We have merged your PR successfully.
