### ISSUE TITLE
GOSA36 - Add Embedded Map to Contact US screen

### ISSUE THREAD

**Issue by VarunAthreya** [GameofSource-GFG/Android-Development#97]
Add the Embedded Map component at bottom of the Contact US screen

**Comment by singhtaran1005** [comment]
assign me

**Comment by VarunAthreya** [comment]
@singhtaran1005  you can start working on this.

**Comment by AVS18** [comment]
@singhtaran1005 thank you for the contribution. You have received 5 points for the contribution. We have merged your PR successfully.
